name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies (minimal)
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn xgboost joblib pytest imbalanced-learn networkx pyvis streamlit
      - name: Run tests
        run: |
          pytest -q
